apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configstore-connector
  name: configstore-connector
  namespace: mw-sit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configstore-connector
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: configstore-connector
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/mw/middleware-configstoreconnector@sha256:fdbcd2ac8326fa40ebb2e58fea867a716ceeda072d784378554519298f2be717
        name: configstore-connector
        env:
            - name: APPDB_URL
              value: 'jdbc:oracle:thin:@192.168.50.10:1521:orcl?autoReconnect=true&useSSL=false'
            - name: APPDB_URL_USERNAME
              value: BPM_APPDB
            - name: APPDB_URL_PASSWORD
              value: BPM_AppDB
            - name: JAEGER_SERVICE_NAME
              value: CONFIGSTORE_CONNECTOR
            - name: JAEGER_ENDPOINT
              value: 'https://jaeger-istio-system.apps.ocp4-cluster-001.int.dhdigital.co.in'
        resources: {}
