apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argocd
spec:
  destination:
    namespace: bgd
    server: https://api.ocp4-cluster-001.int.dhdigital.co.in:6443
  project: default
  source:
    path: apps/bgd/overlays/bgd
    repoURL: https://github.com/imdjaffersadiq/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
